### ISSUE TITLE
View Converter Fails There Is A Comment

### ISSUE THREAD

**Issue by nickshffer** [littleK0i/SnowDDL#108]
If a view has a comment then the converter will not properly parse the ddl.

The [regex statement](https://github.com/littleK0i/SnowDDL/blob/e43f17e6421b7325c36864b5e45ab8d372ce5d4a/snowddl/converter/view.py#L11) for parsing the view definition fails to find any matches if the view has a comment (which would come between the closing paren of the column defs and the `\sas` .

As a result, `view_text` is in effect the full body of the view ddl, which causes:

```
...
(
    message   =>  SQL compilation error:
syntax error line 18 at position 0 unexpected 'create'.
...
```

**Comment by littleK0i** [comment]
Please try `0.28.2`. I've relaxed view parsing regexp a bit.

Unfortunately, there seems to be no way of getting "pure" SQL query text from Snowflake metadata, so current methods are prone to parsing errors.
