### ISSUE TITLE
ValueError when attempting to specify secrets in procedure

### ISSUE THREAD

**Issue by tarobun** [littleK0i/SnowDDL#112]
**Describe the bug**
When attempting to specify **secrets** in a procedure, snowddl returns an error:

`ValueError: too many values to unpack (expected 2)`

**Expected behavior**
No errors, procedure created with **secrets**

**Attach log**
> 2024-07-11 21:49:12.717 - WARNING - [send().yaml]: Traceback (most recent call last):
>  File "/xxx/.venv/lib/python3.10/site-packages/snowddl/parser/abc_parser.py", line 38, in parse_schema_object_files
    callback(file)
>  File "/xxx/.venv/lib/python3.10/site-packages/snowddl/parser/procedure.py", line 152, in process_procedure
    secrets=self.get_secrets(f),
>  File "/xxx/.venv/lib/python3.10/site-packages/snowddl/parser/procedure.py", line 203, in get_secrets
    return {k: build_schema_object_ident(self.env_prefix, v, f.database, f.schema) for k, v in f.params.get("secrets")}
>  File "/xxx/.venv/lib/python3.10/site-packages/snowddl/parser/procedure.py", line 203, in <dictcomp>
    return {k: build_schema_object_ident(self.env_prefix, v, f.database, f.schema) for k, v in f.params.get("secrets")}
>
> ValueError: too many values to unpack (expected 2)

**Attach YAML config (if applicable)**
`secrets:`
`  cred: api_key`

`returns: VARCHAR(100)`

`body:`
`  SELECT 1`

**Comment by littleK0i** [comment]
@tarobun , please check `0.29.2`. Should be fixed.

Diff: https://github.com/littleK0i/SnowDDL/commit/05e87366d367f8bd72b86c90db73c712f370211f

Oddly enough, `FUNCTION` is good. It only affects `PROCEDURE`.

**Comment by tarobun** [comment]
Working now. Thanks for the quick fix.
