### ISSUE TITLE
config.remove_blueprint() is not removing blueprint

### ISSUE THREAD

**Issue by MaRo99382** [littleK0i/SnowDDL#115]
**Describe the bug**
Calling the method remove_blueprint(bp: AbstractBlueprint) on a SnowDDLConfig object does not remove the blueprint from the config object.
I noticed this while creating a programmatic config.
Upon inspection of <https://github.com/littleK0i/SnowDDL/blob/master/snowddl/config.py> it seems to me the method implementation does only raise an error when called with a non-existent blueprint but does not actually remove the blueprint from the config if it exists:

``` 
def remove_blueprint(self, bp: AbstractBlueprint):
        if str(bp.full_name) not in self.blueprints.get(bp.__class__, {}):
            raise ValueError(f"Blueprint with type [{bp.__class__.__name__}] and name [{bp.full_name}] does not exist in config")
```            

**Expected behavior**
Calling the method remove_blueprint(bp: AbstractBlueprint) on a SnowDDLConfig object should remove the blueprint object from the collection of blueprints of the config object.

**Comment by littleK0i** [comment]
Thank you for pointing this out. Should be fixed in `0.30.4+`.

Oddly enough,  had a test for `remove_blueprint()`, and it was passing somehow.
