### ISSUE TITLE
Error when trying to grant external access integration usage to a technical role

### ISSUE THREAD

**Issue by tarobun** [littleK0i/SnowDDL#119]
**Describe the bug**
Unable to grant a technical role with permission to external access integration.

**Expected behavior**
Able to grant external access integration usage to a technical role.

**Attach log**
2024-09-05 05:00:32.017 - WARNING - Resolved ROLE [FS_INTEGRATION__T_ROLE]: ERROR
(
    message   =>  SQL compilation error:
syntax error line 1 at position 24 unexpected 'ACCESS'.
    errno     =>  1003
    sqlstate  =>  42000
    sfqid     =>  01b6d20c-0001-72f1-0001-1afe003644f6
    sql       =>  GRANT USAGE ON EXTERNAL ACCESS INTEGRATION "FS_API_ACCESS_INTEGRATION" TO ROLE "FS_INTEGRATION__T_ROLE"
)

**Attach YAML config (if applicable)**
fs_integration:
  grants:
    EXTERNAL_ACCESS_INTEGRATION:USAGE:
      - fs_api_access_integration

**Comment by littleK0i** [comment]
Good find. Fixed in `0.31.1`.

Thank you.

**Comment by tarobun** [comment]
Working now. Thanks again for the speedy fix!

**Comment by tarobun** [comment]
Actually, I was doing more testing and saw it revoking and granting "usage" permission every time now:

> REVOKE USAGE ON INTEGRATION "FS_AP_ACCESS_INTEGRATION" FROM ROLE "FS_INTEGRATION__T_ROLE";
> GRANT USAGE ON INTEGRATION "FS_API_ACCESS_INTEGRATION" TO ROLE "FS_INTEGRATION__T_ROLE";

**Comment by littleK0i** [comment]
@tarobun , let's try `0.31.2`.

I've added custom `__eq__` method for `Grant` object, which should take this edge case into account.

Snowflake does not return specific type of integration when we call `SHOW GRANTS`, so we basically do not know the integration type.

**Comment by tarobun** [comment]
Looks good now!
