### ISSUE TITLE
Virtual Columns / Column Expressions?

### ISSUE THREAD

**Issue by JohnL4** [littleK0i/SnowDDL#126]
**Is your feature request related to a problem? Please describe.**
I'm using snowddl-convert and snowddl-singledb to compute deltas against our git repo and apply them to a target environment. (After using schemachange to jam the head of the git repo into a scratch d/b.)

**Describe the solution you'd like**
Would be nice if virtual column definitions survived this process (looks like snowddl-convert doesn't preserve it, for starters).

**Describe alternatives you've considered**
Our fallback position (and maybe even preferred) might be to use default values, not virtual column expressions. Implication is that the column data must be maintained if other pertinent changes occur elsewhere, but most of our data is read-only anyway.

--------------------

Does SnowDDL support virtual columns? I looked at the table converter code and didn't see any reference to the ``expression`` column from ``DESC TABLE``, so... no?

I also saw issue #16 , so I know you weren't super-happy to do it in 2022, and Snowflake seems to have changed the syntax from what was in that issue and today (``AS`` keyword now seems to be required).

[Edit: Possibly-better-option number 2: views.]

**Comment by littleK0i** [comment]
Try adding:
```
            if c["expression"]:
                col["expression"] =c["expression"]
```

Before this part: https://github.com/littleK0i/SnowDDL/blob/master/snowddl/converter/table.py#L141-L142

If it works, I'll add it to converter code. Virtual columns are banned in all setups I have access to, so it is a bit hard to test naturally.

---

The best solution is switch to VIEWs, of course. Virtual columns may create various issues with column-lineage tools. Also, CREATE / INSERT queries with `SELECT *` may not work as intended.

It just complicates things for no good reason.

**Comment by JohnL4** [comment]
> Virtual columns are banned in all setups I have access to

That part's telling. :)

We've decided to move our virtual columns to views, at least for now (we don't really like them, either), so I'm not going to pursue this any farther. Any future person (including possibly future me) can pick up from here, I guess.

Thanks!

**Comment by littleK0i** [comment]
Added in `0.33.0`.
