### ISSUE TITLE
Add support for network rule only attachment to network policies

### ISSUE THREAD

**Issue by apd-bbaker** [littleK0i/SnowDDL#130]
**Is your feature request related to a problem? Please describe.**
Snowflake has [updated their best practice recommendation](https://docs.snowflake.com/en/user-guide/network-policies) to state that allowed/blocked IP ranges should be captured in network rules that are then attached to network policies rather than specifying them directly in the network policy. This capability will eventually be deprecated by Snowflake.

**Describe the solution you'd like**
Update network policy object in SnowDDL to make the allowed_ip_range element optional. Add additional network_rule element to network_policy and make one or the other required.

**Describe alternatives you've considered**
Snowflake still supports specifying allowed_ip_range directly on the network_policy object, so the interim solution is to leave them on the network_policy.

**Additional context**
[Recommendation from Snowflake](https://docs.snowflake.com/en/user-guide/network-policies)

**Comment by littleK0i** [comment]
I'll release update for NETWORK_POLICIES soon.

Snowflake introduced a lot of additional bs around NETWORK_RULES. For example, it is not possible to drop a rule if it is connected to a network policy. But since NETWORK_RULES are schema-level objects, now it is no longer possible to drop DATABASE or SCHEMA containing such rule.

Quite annoying. I've implemented a few workaround, but not sure if it is possible to cover absolutely everything and keep reasonable performance.

**Comment by littleK0i** [comment]
@apd-bbaker , please try version `0.33.0`.

Network policy config: https://docs.snowddl.com/basic/yaml-configs/network-policy

You may also use new config `ACCOUNT POLICY` to assign ACCOUNT-level policy: https://docs.snowddl.com/basic/yaml-configs/account-policy

Internal changes are substantial. If you notice any problems, please let me know.

**Comment by apd-bbaker** [comment]
@littleK0i account_policy and network_policy/rule changes are looking good. I'm running into a strange issue now with apply though where the role created specifically for snowddl to execute doesn't have the necessary permissions to create a new warehouse within the account.

I'm pretty sure I have everything correctly configured as this was working great before, but I may have been approaching it incorrectly. Content of the initial creation script to set up SnowDDL service account objects is below. Any tips on where I might be missing the mark?

```
/********************************************************************/
/* Set up default objects used by SnowDDL to manage the platform */
/********************************************************************/
/* Define variables for object creation */
    set role = 'platform_admin';
    set user = 'svc_manage_snowddl';
    set password = '<strong_password>';
    set warehouse = 'manage_wh';


/* Create management user and role objects */
    -- Use the built-in super user role
    use role accountadmin;

    -- Create the elevated user role
    create or replace role identifier($role);

    -- Grant elevated role to parent built-in Snowflake role
    grant role identifier($role) to role accountadmin;

    -- Grant built-in Snowflake admin roles to new role
    grant role sysadmin to role identifier($role);
    grant role securityadmin to role identifier($role);

    -- Create new admin service user
    create or replace user identifier($user)
        display_name = 'Service-Manage-SnowDDL'
        comment = "Service account used by SnowDDL to manage the Snowflake platform"
        password = $password
        default_role = $role;

    -- Grant admin role to user
    grant role identifier($role) to user identifier($user);



/* Create default user's warehouse for performing operations */
    -- Use the built-in super user role
    use role accountadmin;

    -- Create the management warehouse
    create or replace warehouse identifier($warehouse)
        warehouse_size = 'XSMALL'
        auto_suspend = 60
        auto_resume = true
        initially_suspended = true;

    -- Grant necessary access to platform role
    grant usage,operate on warehouse identifier($warehouse) to role identifier($role);

    -- Set as default wh for user
    alter user identifier($user) set default_warehouse = $warehouse;



/* Enable enhanced functionality for share management */
    -- Use the built-in super user role
    use role accountadmin;

    -- Grant necessary share management permissions
    grant create share on account to role identifier($role);
    grant override share restrictions on account to role identifier($role);



/* WARNING: Destroy platform admin objects */
    -- drop role identifier($role);
    -- drop warehouse identifier($warehouse);
    -- drop user identifier($user);
```



```
snowddl -a $SNOWFLAKE_DEFAULT_ACCOUNT -u svc_manage_snowddl -k $SNOWDDL_PRIVATE_KEY_PATH --passphrase $SNOWDDL_PRIVATE_KEY_PASSPHRASE -r platform_admin -w manage_wh --env-admin-role accountadmin --apply-unsafe --refresh-future-grants --env-prefix dev apply
```

```
2024-10-11 22:02:51.731 - INFO - Snowflake version = 8.38.3 (ENTERPRISE), SnowDDL version = 0.33.0
2024-10-11 22:02:51.731 - INFO - Account = XXXXXXXX, Region = AWS_US_WEST_2
2024-10-11 22:02:51.731 - INFO - Session = 31411977766781326, User = SVC_MANAGE_SNOWDDL
2024-10-11 22:02:51.731 - INFO - Role = DEV__PLATFORM_ADMIN, Warehouse = MANAGE_WH
2024-10-11 22:02:51.731 - INFO - Roles in session = SYSADMIN,SECURITYADMIN
2024-10-11 22:02:51.732 - INFO - ---
2024-10-11 22:02:52.245 - WARNING - Resolved WAREHOUSE [DEV__MANAGE_WH]: ERROR
(
    message   =>  SQL access control error:
Insufficient privileges to operate on account 'XXXXXXX'
    errno     =>  3001
    sqlstate  =>  42501
    sfqid     =>  01b7a08a-0003-dbf7-006f-9907010771ba
    sql       =>  CREATE WAREHOUSE "DEV__MANAGE_WH"
```

Which in turn appears to cause errors of this sort also:
```
2024-10-11 22:03:58.455 - WARNING - Resolved NETWORK_POLICY [DEV__ALLOW_LAN]: ERROR
(
    message   =>  No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

    errno     =>  606
    sqlstate  =>  57P03
    sfqid     =>  01b7a08b-0003-dbf8-006f-990701076d2a
    sql       =>  SELECT * FROM TABLE(snowflake.information_schema.policy_references(policy_name => 'DEV__ALLOW_LAN', policy_kind => 'NETWORK_POLICY'))
```

**Comment by littleK0i** [comment]
Script looks good.

Initial context in logs looks good as well. It shows both `SYSADMIN` and `SECURITYADMIN` roles. `SYSADMIN` normally includes `CREATE WAREHOUSE`, unless it was altered somehow. You may check grants to SYSADMIN using this command:

```
show grants to role sysadmin;
```

A few problems I can see:

1. Try to remove MANAGE_WH from SnowDDL config. It should be created &granted manually, and it already happens in set up script.
2. These options can be removed `-r platform_admin -w manage_wh`. Default role and default warehouse come from user parameters.
3. This option may potentially be removed `--env-admin-role accountadmin`. It is only relevant when SnowDDL admin role has `ACCOUNTADMIN`.

**Comment by littleK0i** [comment]
In theory, unsuccessful `CREATE WAREHOUSE` might be resetting current warehouse in session.

Currently we reset it back for successful `CREATE WAREHOUSE` commands, but not for errors. Maybe errors should be included as well.

**Comment by littleK0i** [comment]
Double-checked this.

This error does not cause current session to lose active warehouse. So it must be something else.

If issue persists after removing `manage_wh` from config, we may need to take a look at full log (CLI option `--show-sql`).

**Comment by apd-bbaker** [comment]
@littleK0i Found a big part of the issue. In the initial creation script the defaults assigned to the snowddl service account were not capitalized, so Snowflake apparently had an issue with that when setting them upon start of session. Corrected that, removed extraneous arguments, dropped all old objects with different ownership, and have been able to re-align everything and get a clean apply run again.

**Comment by littleK0i** [comment]
Ah, classic.

This is why SnowDDL enforces upper-cased identifiers and adds double-quotes (`"`) for identifiers at all times. It helps to mitigate lots of non-obvious issues.
