### ISSUE TITLE
Allow YML extension in addition to YAML

### ISSUE THREAD

**Issue by apd-bbaker** [littleK0i/SnowDDL#133]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be great to allow YML as well as YAML file extensions as both are commonly found in codebases. It's tripped us up a bit when we realize we missed a keystroke in the filename and spent a lot of time troubleshooting the object only to realize it was that simple difference.

**Describe alternatives you've considered**
N/A

**Additional context**
I'd like to take a crack at the code change for this issue as it seems fairly straightforward.

**Comment by littleK0i** [comment]
It is an interesting topic.

In theory, it should be easy to update the code to support both `YAML` and `YML`. But it would quickly lead to unintended consequences with configs having mixture of extensions. Some files will be `.yaml` and other files will be `.yml`, unless we use pre-commit hook or linter. This naturally creates mess, and we want to avoid mess.

Another possible option is to add CLI parameter which allows to change extension entirely and ask all config files to be `.yml`. But now we need to remember about one more parameter, and configs become less portable overall. It becomes harder to copy & paste or share parts of config.

In the end, it might be easier to stick with [officially recommended](https://yaml.org/faq.html) `.yaml` extension and call it a day. Ultimately, I would blame people responsible for standards for not enforcing one way or another.

**Comment by apd-bbaker** [comment]
YAML/YML doesn't make much difference in my mind so prefer the option to choose one or the other based on preference of the team building the solution. What about a middle ground - a warning that detects YML extensions and warns that it should be renamed? That would do a little more for enforcement than just ignoring them.

**Comment by littleK0i** [comment]
In theory, we can go further and highlight all files which exist in config directory, but were never picked up by any parsers. It would help to find all types of naming mistakes, not only extensions.

The only problem is.. I know some people use underscore to "comment" some directories with object types. E.g. rename `table` to `_table`, and it causes SnowDDL to ignore this part. Guess it will no longer be possible.

Maybe we can add it as an option or as a pre-commit hook for Git.

**Comment by apd-bbaker** [comment]
@littleK0i My concern is that this places a hard dependency on Git to do the work of app validation logic, which can lead down a dangerous path when logic becomes more complex later. It seems cleaner and more contained to have the app perform these sorts of validations as part of the general structure checks ahead of parsing the yaml files, no?

**Comment by littleK0i** [comment]
@apd-bbaker , @kokorin , some changes were introduced in `0.36.0`:

Both `.yml` and `.yaml` extensions for config files are now supported. If two files have the same name, but different extensions, validation error will be raised.

It is now possible to detect "unused" config files which were not consumed by any parsers. CLI option `--show-unused-files`, turned off by default.
