### ISSUE TITLE
Please add unsafe_alters to output comments when building table CTAS statement

### ISSUE THREAD

**Issue by JohnL4** [littleK0i/SnowDDL#141]
**Is your feature request related to a problem? Please describe.**
I'm still using snowddl-convert/singledb plan to generate sql to update a target Snowflake d/b to match our git repo. One of the problems I'm trying to solve is detecting when a CTAS statement implicitly drops a column, so I can flag the generated plan sql for human review/approval. It looks like, within ``TableResolver.compare_object()`` there is a variable, ``unsafe_alters`` that records the columns that are getting dropped (and probably some other stuff, too). It would make my problem case (column implicitly dropped by CTAS) easier to detect if the contents of that variable were emitted as a comment (ideally, one item per line), the same as ``replace_reasons``.

**Describe the solution you'd like**
This, or something like it:
```
        if replace_reasons:
            replace_query = "\n".join(f"-- {r}" for r in replace_reasons) \
                + "\n" + "\n".join( f"-- {a}" for a in unsafe_alters) \                <------------------------- this
                + "\n" + str(self._build_create_table(bp, snow_cols))
```

**Describe alternatives you've considered**
Could detect CTAS in generated plan and issue my own sql query for DESC TABLE, but it's already happening in snowddl, and getting parsed and processed the same way I would.

Could also make the above change in my own local version of snowddl, but that would require an internal fork and following snowddl version updates.

**Additional context**
None.

**Comment by littleK0i** [comment]
In theory, we may add SQL comments about removed columns between column list and FROM.

```sql
CREATE OR REPLACE TABLE abc (...)
AS
SELECT col1
    , col2
    , col3
    -- col4 was removed
    -- col5 was removed
FROM abc
```

Showing everything is probably an overkill, since actual review should happen in Git for most users.

**Comment by littleK0i** [comment]
Added additional notice about columns being dropped after replace reasons.

For example (see 2nd line):
```sql
-- Data type for column REGISTER_TS was changed from TIMESTAMP_TZ(3) to TIMESTAMP_NTZ(3)
-- Column NAME is about to be dropped
CREATE OR REPLACE TABLE "PYTEST__DB1"."SC1"."TB004_TB1"
(
      "ID" NUMBER(10,0)
    , "STATUS" VARCHAR(255)
    , "REGISTER_TS" TIMESTAMP_NTZ(3)
)
COPY GRANTS
AS
SELECT
      "ID" AS "ID"
    , "STATUS" AS "STATUS"
    , "REGISTER_TS"::TIMESTAMP_NTZ(3) AS "REGISTER_TS"
FROM "PYTEST__DB1"."SC1"."TB004_TB1";
```

**Comment by JohnL4** [comment]
Thanks, I'll check it out!

As an aside, my plan is to generate an update script via ``snowddl-singledb plan`` and flag it for more-intensive human review before it gets run. One condition is this one (CTAS drops columns), but in future, I also hope to catch other possible-data-loss issues like shrinking a varchar column or reducing precision on a number (just as examples). Or issues that might cause the update script to bomb out, although that's a bit more ambitious (might require actual data inspection).

**Comment by littleK0i** [comment]
It might be worth to simply review everything. Especially if config and ETL + SQL transformations are in the same repository.

**Comment by JohnL4** [comment]
Yeah. Sadly, they're not in the same repo (yet; and may never be). Also, people here take renaming very lightly, both in design/coding and review. Can't speak to the issue of shrinking columns yet.

**Comment by JohnL4** [comment]
Ok, we are merging our internal changes into our pipelines, so this change is good from our perspective.

Many thanks!!
