### ISSUE TITLE
AWS S3 External Stage informational property for directory_notification_channel causing ALTER statement

### ISSUE THREAD

**Issue by MartinCairnsSQL** [littleK0i/SnowDDL#144]
**Describe the bug**
The DIRECTORY_NOTIFICATION_CHANNEL property in the DESC STAGE output is informational but isn't ignored so S3 stages are always picked up as having a change.

Below is the only page in the Snowflake documentation which mentions this property.
https://docs.snowflake.com/en/user-guide/data-load-dirtables-auto-s3

**Expected behavior**
The DIRECTORY_NOTIFICATION_CHANNEL property to be ignored in the resolver in the same way as the LAST_REFRESHED_ON property.

**Example output of DESC STAGE**
![image](https://github.com/user-attachments/assets/51d1b993-8ff6-40d3-a470-9eb95a11f958)

**Comment by littleK0i** [comment]
Could make a bit bigger screenshot and include `property_default` column? Maybe we can rely on `property_default` being empty string to detect "read-only" properties.

Naturally, I would love to avoid hardcoding property names as much as possible.

**Comment by littleK0i** [comment]
I guess `AWS_SNS_TOPIC` is one more read-only parameter.

**Comment by MartinCairnsSQL** [comment]
![image](https://github.com/user-attachments/assets/5517fc31-0702-45d0-9dfb-4d2c5f224740)
The AWS_SNS_TOPIC is set in the CREATE/ALTER STAGE for refreshing the directory table automatically for s3, I've used Snowdll to create the stage with it set successfully.

**Comment by littleK0i** [comment]
Alright. It seems currently there is no way to distinguish between normal and "read-only" properties without explicitly hardcoding one or another.

Added explicit skip for `DIRECTORY_NOTIFICATION_CHANNEL` in `0.35.1`. Should help for now, but it would be nice to find a better long term solution.
