### ISSUE TITLE
Business roles absent in business_role.yaml but specified in user.yaml are implicitly created and granted

### ISSUE THREAD

**Issue by kokorin** [littleK0i/SnowDDL#150]
**Describe the bug**
```yaml
#users.yaml
my_user:
  password: '123'
  business_roles:
    - reporter
    - analyst
```

```yaml
#business_role.yaml
analyst: {}
```
No BRole `reporter` is configured, but it is created and granted to `my_user`

**Expected behavior**

I would expect validation error from SnowDDL. It would help in case of typos in user's `business_roles` property or in case of BRole rename.

**Attach log**
```
--- Suggested DDL ---

CREATE ROLE "ANALYST__B_ROLE";

GRANT ROLE "ANALYST__B_ROLE" TO ROLE "SNOWDDL_ADMIN";

CREATE ROLE "MY_USER__U_ROLE";

GRANT ROLE "MY_USER__U_ROLE" TO ROLE "SNOWDDL_ADMIN";

GRANT ROLE "REPORTER__B_ROLE" TO ROLE "MY_USER__U_ROLE";

GRANT ROLE "ANALYST__B_ROLE" TO ROLE "MY_USER__U_ROLE";

CREATE USER "MY_USER"
LOGIN_NAME = 'MY_USER'
DISPLAY_NAME = 'MY_USER'
DEFAULT_ROLE = "MY_USER__U_ROLE"
PASSWORD = '123' ;

GRANT ROLE "MY_USER__U_ROLE" TO USER "MY_USER";
```

Update: it appears that `apply` command fails in that scenario, but not `plan`:
```
2024-11-21 10:33:27.868 - WARNING - Resolved ROLE [<REDACTED>__U_ROLE]: ERROR
(
    message   =>  SQL compilation error:
Role '<REDACTED>__B_ROLE' does not exist or not authorized.
    errno     =>  2003
    sqlstate  =>  02000
    sfqid     =>  01b88479-0105-6df8-0001-<REDACTED>
    sql       =>  GRANT ROLE "<REDACTED>__B_ROLE" TO ROLE "<REDACTED>__U_ROLE"
)
```

**Comment by kokorin** [comment]
I believe cross-references between blueprints can be validated, i.e. BRole granted Global Roles may have no validation, but references to WH, BRoles or TRoles should be validated.
I will try to find some time this weekend to take a look.

**Comment by littleK0i** [comment]
The question is how to organize it in the code to make such checks relatively "clean".

The most simple solution is to add a generic function to AbstractParser throwing error:

```
Object XXX of type YYY does not exist in config
```

... but it would be nice to know the context. For example:

```
User XXX references business role YYY which does not exist in config
```

That's great, but code would look like tons of IF statements. Maybe it is not too bad if moved into a dedicated "validate" function.

**Comment by littleK0i** [comment]
At this moment exceptions during parsing include path to file which caused an exception. Works very well for schema objects (tables, views, etc.). Does not work so well for account-level objects, such as business roles, since all roles are in the same file. And some configs may have hundres of such roles.

**Comment by littleK0i** [comment]
Btw, validator implementation is very close to your original proposal.

The only major difference is exception handling using "one-exception-per-blueprint". In the original code an exception in any blueprint would prevent validation from running for other blueprints.

**Comment by kokorin** [comment]
Thank you for the update and improved validation feature! It will really help us in adopting SnowDDL.
