### ISSUE TITLE
Support GRANT EXECUTE TASK

### ISSUE THREAD

**Issue by kokorin** [littleK0i/SnowDDL#152]
**Is your feature request related to a problem? Please describe.**
We create tasks in Snowflake to clean up some test schemas (using DBT). 
EXECUTE TASK privilege is granted on account level, unfortunately it's not possible to do so.

**Describe the solution you'd like**
Dedicated SnowDDL object to manage account-level grants to Business Roles. 

**Describe alternatives you've considered**
As of now I'm going to create custom role, grant it EXECUTE TASK and grant that role ro Business Role through `global_roles`.

**Comment by littleK0i** [comment]
`EXECUTE TASK` should be granted on schema level using `owner_account_grants`: https://docs.snowddl.com/basic/yaml-configs/schema

It is mentioned on documentation page describing tasks: https://docs.snowddl.com/basic/yaml-configs/task

**Comment by kokorin** [comment]
Indeed, sorry for the issue!

**Comment by kokorin** [comment]
Sorry again for re-opening the issue, but I realized that account-level grants are specified from DB or Schema owner.
To run DBT we use business roles only, and in that case it can be more convenient to grant account-level privileges on business role in addition to (or instead of) database or schema owner roles.

What do you think?

**Comment by littleK0i** [comment]
Tasks run with task owner privileges. Task owner is "schema owner" role. There is no point granting `EXECUTE TASK` to business roles.

But there you may grant schema owner role to DBT-related business role, and it should work just fine. DBT will inherit all privileges from schema owner, should be able to create & execute tasks.

It might be invalid if Snowflake changed something recently. Please let me know if they did.
