### ISSUE TITLE
Support read-only databases: replicas and shares

### ISSUE THREAD

**Issue by kokorin** [littleK0i/SnowDDL#153]
**Is your feature request related to a problem? Please describe.**
It's possible to manage grants on read-only databases using latest SnowDDL, but sometimes it's not very convenient.
For example, if DB's comment doesn't match a comment defined in `/<database>/params.yaml` SnowDDL will try to alter the DB and set/update comment. Also there is no sense to grant delete schema or delete table privileges on read-only DBs.

**Describe the solution you'd like**
I can think of extra property in DB's `params.yaml` or additional YAML files in database folder.

**Describe alternatives you've considered**
We defined database's `params.yaml` with exactly the same comment and `is_sandbox: true`.
Additionally we are going to add custom read-only permission model.

**Comment by littleK0i** [comment]
You may grant shares to business roles using `share_read`: https://docs.snowddl.com/basic/yaml-configs/business-role

You may grant shares to schema owner roles using `owner_share_read`: https://docs.snowddl.com/basic/yaml-configs/schema

It should be possible to grant database roles from shares using `global_roles` by using syntax with "dot" in the middle: `<share_name>.<database_role_name>`.

Replicas are kinda interesting. Snowflake has multiple implementations of this feature, but all of them seems a bit useless to me in the context of the cloud. It increases Snowflake bill while producing very little real value. But I am happy to learn about valid use-cases and potential approaches to solve them.

At this moment it should be possible to create a replica, create a global role with grants and assign to business or schema roles via `global_roles` / `owner_global_roles`. Should not be a major blocker.

**Comment by kokorin** [comment]
Regarding use-case: we replicate data from one SF account  to another as it's not possible (as far as I know) to share a DB across clouds or regions in the same cloud. SF supports replication groups, but it requires accountadmin role to create a group or to operate with it

Thank you for the clarification of business-role configuration!

Please, let me know if you would like to have more details about our use-case, or feel free to close the issue otherwise.

**Comment by littleK0i** [comment]
As far as I know, Snowflake has a "legacy" replication for databases only `CREATE DATABASE ... AS REPLICA`: https://docs.snowflake.com/en/sql-reference/sql/create-database#database-replication-usage-notes

It is simple, but Snowflake does not recommend to use it anymore.

And they also have a super-complex account replication feature: https://docs.snowflake.com/en/user-guide/account-replication-intro

Account replication can sync a lot of object types, including roles. But they also have a lot of various limitations, and if your use-case does not match their limitations perfectly, it may not end well.

Why not just copy data manually via basic ETL process, especially if some reasonable lag is permitted? Export from one account and import into another. It should be cheaper in general, and you'll full control over every aspect of replication.
