### ISSUE TITLE
Database and Schema params.yaml not parsed by 0.36.0

### ISSUE THREAD

**Issue by MartinCairnsSQL** [littleK0i/SnowDDL#156]
**Describe the bug**
The params.yaml files for databases and schema are not loaded by 0.36.0

**Expected behavior**
0.35.1 reads the params.yaml files and sets the database and schema parameters, the params.yamls are listed with the --show-unused-files setting in 0.36.0

**Attach log**
-- 0.35.1 log
2024-11-25 12:36:10.973 - INFO - Snowflake version = 8.44.2 (BUSINESS_CRITICAL), SnowDDL version = 0.35.1
2024-11-25 12:36:10.973 - INFO - Account = ?, Region = ?
2024-11-25 12:36:10.973 - INFO - Session = ?, User = ?
2024-11-25 12:36:10.973 - INFO - Role = ?, Warehouse = ?
2024-11-25 12:36:10.973 - INFO - Roles in session = ?
2024-11-25 12:36:10.973 - INFO - ---
2024-11-25 12:36:21.176 - INFO - Resolved PIPE [?]: REPLACE
2024-11-25 12:36:21.176 - INFO - Resolved PIPE [?]: REPLACE
2024-11-25 12:36:22.009 - INFO - Executed 0 DDL queries, Suggested 4 DDL queries
-- 0.36.0
2024-11-25 12:37:51.037 - INFO - Snowflake version = 8.44.2 (BUSINESS_CRITICAL), SnowDDL version = 0.36.0
2024-11-25 12:37:51.037 - INFO - Account = ?, Region = ?
2024-11-25 12:37:51.037 - INFO - Session = ?, User = ?
2024-11-25 12:37:51.037 - INFO - Role = ?, Warehouse = GENERAL_XS
2024-11-25 12:37:51.037 - INFO - Roles in session = ?
2024-11-25 12:37:51.037 - INFO - ---
2024-11-25 12:37:51.919 - INFO - Resolved DATABASE [CDP]: ALTER
...
--- Suggested DDL ---

ALTER DATABASE "?" SET
COMMENT = NULL;

**Comment by littleK0i** [comment]
Could you share a full message returned by `--show-unused-files`?

**Comment by MartinCairnsSQL** [comment]
The file_key and self.all_file_paths are in different formats and the database level keys in the format {database}\\{schema}\\{type}
(Pdb) w
  <frozen runpy>(198)_run_module_as_main()
  <frozen runpy>(88)_run_code()
  c:\users\m_cairns\source\repos\dataservices\venv\scripts\snowddl.exe\__main__.py(7)<module>()
-> sys.exit(entry_point())
  c:\users\m_cairns\source\repos\dataservices\venv\lib\site-packages\snowddl\app\base.py(707)entry_point()
-> app = BaseApp()
  c:\users\m_cairns\source\repos\dataservices\venv\lib\site-packages\snowddl\app\base.py(42)__init__()
-> self.config = self.init_config()
  c:\users\m_cairns\source\repos\dataservices\venv\lib\site-packages\snowddl\app\base.py(385)init_config()
-> parser.load_blueprints()
  c:\users\m_cairns\source\repos\dataservices\venv\lib\site-packages\snowddl\parser\schema.py(79)load_blueprints()
-> database_params = self.parse_single_file(f"{database_name}/params", database_json_schema)
  c:\users\m_cairns\source\repos\dataservices\venv\lib\site-packages\snowddl\parser\abc_parser.py(42)parse_single_file()
-> path = self.scanner.get_single_file_path(file_key)
> c:\users\m_cairns\source\repos\dataservices\venv\lib\site-packages\snowddl\parser\_scanner.py(37)get_single_file_path()
-> if file_key in self.all_file_paths:
(Pdb) l
 32             return self.schema_dir_paths[self._normalise_key(database_key)]
 33
 34         def get_single_file_path(self, file_key: str) -> Optional[Path]:
 35             file_key = self._normalise_key(file_key)
 36
 37  ->         if file_key in self.all_file_paths:
 38                 self.accessed_files.add(file_key)
 39                 return self.all_file_paths[file_key]
 40
 41             return None
 42
(Pdb) pp file_key, self.all_file_paths
('cdp/params',
 {'cdp\\cdp_eod\\params': WindowsPath('C:/Users/m_cairns/source/repos/dataservices/config/cdp/cdp_eod/params.yaml')

**Comment by MartinCairnsSQL** [comment]
I've tested a change to _normalise_key() in _scanner.py to fix the file_key for Windows this gives the same differences as the previous version.

```
    def _normalise_key(self, key: str):
        key = key.replace('\\','/')
        return key.lower()
```

**Comment by littleK0i** [comment]
Yeah, `.as_posix()` call added in https://github.com/littleK0i/SnowDDL/commit/eb94bc779569469961767fa1fd2c4d5b84206bbc does the same replace internally.

**Comment by MartinCairnsSQL** [comment]
0.36.1 fixes the issue.

Thanks
