### ISSUE TITLE
Trailing paren is stripped from DEFAULT expression for a column

### ISSUE THREAD

**Issue by JohnL4** [littleK0i/SnowDDL#159]
**Describe the bug**
(I hate to be the constant bearer of bad news. I'm going to continue investigating, but I wanted to get this issue in the pipeline.)

We have a column with an expression for the default value, and the expression comes out of DESC TABLE (or whatever the converter uses) and is recorded by ``snowddl-convert`` as follows:

```
columns:
  # ...Other columns...
  metal_level_cd:
    type: VARCHAR(1)
    default: IFF(METAL_LEVEL_XWALK.INT_METAL_LEVEL_TXT IS NULL, SYSTEM$NULL_TO_TEXT(null),
      SUBSTR(METAL_LEVEL_XWALK.INT_METAL_LEVEL_TXT, 1, 1))
    comment: 'Legacy Field Name: [METALLEVELCODE], Table Name: [DBO].[METALLEVELCROSSWALK]'
```

(Not sure if relevant, but this is the last column in the table.)

However, when ``snowddl-singledb`` generates SQL, it comes out looking like this:

```
CREATE OR REPLACE TABLE "VP_INT_CLIENT"."REF_DW_LEGACY"."METAL_LEVEL_XWALK"
(
  -- Other columns
    , "METAL_LEVEL_CD" VARCHAR(1) DEFAULT IFF(METAL_LEVEL_XWALK.INT_METAL_LEVEL_TXT IS NULL, SYSTEM$NULL_TO_TEXT(null), SUBSTR(METAL_LEVEL_XWALK.INT_METAL_LEVEL_TXT, 1, 1) COMMENT 'Legacy Field Name: [METALLEVELCODE], Table Name: [DBO].[METALLEVELCROSSWALK]'
)
COPY GRANTS
AS
SELECT
  -- yada yada
    , "METAL_LEVEL_CD" AS "METAL_LEVEL_CD"
FROM "VP_INT_CLIENT"."REF_DW_LEGACY"."METAL_LEVEL_XWALK";
```

(Note the trailing double paren of the expr got changed into one paren.)

This obviously results in a syntax error and the generated script fails.

**Expected behavior**
Generated expression in SQL is complete, with all required characters.

**Attach log**
No log at the moment, but: Snowflake version = 8.44.2 (BUSINESS_CRITICAL), SnowDDL version = 0.36.2

**Attach YAML config (if applicable)**
No yaml at the moment, other than the above.

**Comment by littleK0i** [comment]
Does adding quotes around this value change anything?

**Comment by JohnL4** [comment]
It's possible the fault is in my post-processing. :") Still investigating...

**Comment by JohnL4** [comment]
Yeah, oops, totally my fault. Now I get to debug my _own_ code. :/
