### ISSUE TITLE
Import existing obects

### ISSUE THREAD

**Issue by Stegallo** [littleK0i/SnowDDL#23]
This project is great and I really like the declarative approach.

I think it works perfectly when the database is built from scratch using the tool.

In case of an existing database containing a large number of object, creating the yaml file for each of them can require significant manual effort. Have you by chance considered a way to import existing objects in the configuration? Snowflake allows to script the content of the database, but that gets exported in the form of a SQL script and it cat not immediately be used as is with the tool.

Appreciate your input.
Thanks!

**Comment by littleK0i** [comment]
Thank you for your interest. Yes, I think about this feature quite often.

A few very basic converters are available, but not documented at this moment. Please check CLI options for this command: `snowddl-convert --help`

You may also check [this discussion thread](https://github.com/littleK0i/SnowDDL/discussions/8) for a bit more information.

The main issue with automated conversion is a relatively high amount of time & effort required to implement and maintain this feature. Snowflake keeps adding new options, but many options are still not available for introspection with `DESC` command and `INFORMATION_SCHEMA`.

Currently I am trying to figure out, which object types and options are absolutely required. Implementing all types and not feasible, but we could definitely cover the most frequently used ones.

**Comment by Stegallo** [comment]
Thanks for your reply. I should have checked the discussions tab first.
I will close this issue and refer to that tab further conversation.
