### ISSUE TITLE
Unable to set user session params

### ISSUE THREAD

**Issue by marksabincarnivaluk** [littleK0i/SnowDDL#28]
Hi,

I am unable to set user session params, including network policy. When I set a network policy manually for a user, SnowDDL wants to remove it.

user.yaml:
testuser:
  login_name: test.user@testdomain.local
  default_warehouse: CLUSTER_WH
  business_roles:
    - TESTER
  session_params:
    network_policy: office_only
    query_tag: Test

snowddl --include-object-types user plan

--- Suggested DDL ---

CREATE USER "TESTUSER" 
LOGIN_NAME = 'TEST.USER@TESTDOMAIN.LOCAL'
DISPLAY_NAME = 'TESTUSER'
DISABLED = FALSE
FIRST_NAME = NULL
LAST_NAME = NULL
EMAIL = NULL
DEFAULT_WAREHOUSE = 'CLUSTER_WH'
DEFAULT_NAMESPACE = NULL
DEFAULT_ROLE = "TESTUSER__U_ROLE"
COMMENT = NULL ;

GRANT ROLE "TESTUSER__U_ROLE" TO USER "TESTUSER";

**Comment by littleK0i** [comment]
@marksabincarnivaluk , should be fixed in `0.12.1`. Thank you for pointing this out.

Oddly enough, it was never covered with tests and slipped through during the last round of parameter renaming.

**Comment by marksabincarnivaluk** [comment]
Thank you, working fine in 0.12.1.
