### ISSUE TITLE
Compilation error while creating Procedure with both 'is_execute_as_caller' and 'comment' options are used

### ISSUE THREAD

**Issue by sindhuthirugnanam** [littleK0i/SnowDDL#29]
When creating Stored Procedure with both `is_execute_as_caller` and `comment` options in yaml, compilation error is issued on Snowflake end. For some reason, Snowflake doesn't accept when order of required parameters are changed. For example if I place `COMMENT` after `EXECUTE AS` compilation error occurs. However, the procedure is created successfully when  `COMMENT` parameter is placed before `EXECUTE AS`. 

Refer to the [Snowflake Create Procedure](https://docs.snowflake.com/en/sql-reference/sql/create-procedure.html) documentation.

Procedure Yaml Content:
```
arguments:
  ticket_no: VARCHAR(13)
  flight_id: NUMBER(10,0)
  boarding_no: NUMBER(10,0)
  seat_no: VARCHAR(4)

returns: BOOLEAN

body: |-
  BEGIN
    INSERT INTO boarding_passes (ticket_no, flight_id, boarding_no, seat_no)
    VALUES (:TICKET_NO, :FLIGHT_ID, :BOARDING_NO, :SEAT_NO);

    RETURN TRUE;
  END;

is_execute_as_caller: true

comment: "Test SP Creation with Caller Rights"
```

SQL Compilation Error:
```
2022-12-02 15:35:04.943 - WARNING - Resolved PROCEDURE [SNOWDDL_TEST.DBO.CHECK_IN(VARCHAR,NUMBER,NUMBER,VARCHAR)]: ERROR
(
    message   =>  SQL compilation error:
syntax error line 10 at position 0 unexpected 'COMMENT'.
    errno     =>  1003
    sqlstate  =>  42000
    sfqid     =>  01a8b4d3-0504-336f-0003-3387003240a6
    sql       =>  CREATE OR REPLACE PROCEDURE "SNOWDDL_TEST"."DBO"."CHECK_IN" (
      "TICKET_NO" VARCHAR(13)
    , "FLIGHT_ID" NUMBER(10,0)
    , "BOARDING_NO" NUMBER(10,0)
    , "SEAT_NO" VARCHAR(4)
)
RETURNS BOOLEAN
LANGUAGE SQL
EXECUTE AS CALLER
COMMENT = 'Test SP Creation with Caller Rights'
AS 'BEGIN
  INSERT INTO boarding_passes (ticket_no, flight_id, boarding_no, seat_no)
  VALUES (:TICKET_NO, :FLIGHT_ID, :BOARDING_NO, :SEAT_NO);

  RETURN TRUE;
END;'
)
```

**Comment by littleK0i** [comment]
Thank you for pointing this out.

I'll fix it tomorrow and add some tests for `FUNCTION` and `PROCEDURE` object types.

Snowflake syntax is a bit weird sometimes.

**Comment by littleK0i** [comment]
Please check `0.12.2`. This specific issue should be fixed.

I've also discovered an odd behavior of `TIME` and `TIMESTAMP`-like arguments with non-default precision in functions and procedures. I've added some protection and raised a case with Snowflake support. I'll release tests as soon as I get a reply from them.
