### ISSUE TITLE
Error trying to revoke ownership

### ISSUE THREAD

**Issue by marksabincarnivaluk** [littleK0i/SnowDDL#33]
**Describe the bug**

2023-01-16 14:44:34.042 - WARNING - Resolved ROLE [DEV__MYSCHEMA__OWNER__S_ROLE]: ERROR
(
    message   =>  SQL execution error: OWNERSHIP can only be transferred.
    errno     =>  3937
    sqlstate  =>  23001
    sfqid     =>  01a9b094-0102-2f97-0001-01e200d7576e
    sql       =>  REVOKE OWNERSHIP ON TABLE "DEV_TEST"."MYSCHEMA"."MYTABLE" FROM ROLE "DEV__MYSCHEMA__OWNER__S_ROLE"
)

**Expected behavior**
I'm not sure how this should be handled. In this particular case the database DEV_TEST is a clone of DEV, hence the grants existing in the first place.

**Comment by littleK0i** [comment]
Did you consider using env_prefix feature for testing and development?
https://docs.snowddl.com/guides/other/env-prefix

SnowDDL will create a separate database and separate set of roles. You won't have copy of data, but all the cloning problems will be avoided.

I am not sure if it's possible to support cloning properly. Lots of objects currently cannot be cloned, and it seems to be difficult to "repair" other objects. Please check this list: https://docs.snowflake.com/en/user-guide/object-clone.html

Maybe it would be wise to choose a different path.

It applies to other object management tools as well. I think Terraform should be equally affected by issues related to cloning.

**Comment by marksabincarnivaluk** [comment]
I take the point about cloning, but surely SnowDDL should not try to revoke ownership under any circumstances, since this is an invalid command.

**Comment by littleK0i** [comment]
I agree, I'll add some conditions to prevent this.

**Comment by littleK0i** [comment]
@marksabincarnivaluk , this problem should be fixed in `0.13.0`.
https://github.com/littleK0i/SnowDDL/blob/master/snowddl/resolver/abc_role_resolver.py#L167-L169

It only affects normal grants. OWNERSHIP for future grants still can be dropped.

Thank you for pointing this out.

**Comment by marksabincarnivaluk** [comment]
Thank you. The new version is working fine for me.
