### ISSUE TITLE
Don't DROP unspecified SHARES

### ISSUE THREAD

**Issue by richard-cybersyn** [littleK0i/SnowDDL#46]
**Is your feature request related to a problem? Please describe.**

In our organization we have a separation of `outbound_shares` that are created for the Marketplace vs regular `outbound_shares`. We're using `SnowDDL` to manage our `outbound_shares` for the Marketplace, however we don't want `SnowDDL` to drop shares that aren't specified, e.g. shares that are unrelated to the Marketplace.

**Describe the solution you'd like**

This might be a backwards incompatible change, but I'd for the ability to split the `compare_object` function to support a flag to not run the `drop_grant` function.

https://github.com/littleK0i/SnowDDL/blob/efe72120f2bd8c95c26e1a4b1f3b72796c879eb7/snowddl/resolver/outbound_share.py#L60-L73

This could belong in the `settings.py` file as a flag you initialize at in the config.

**Describe alternatives you've considered**

An alternative, that could be much more significant work, but be much more configurable/modular is to have user-specified configuration on what is considered `safe` vs `unsafe` DDL. This would allow the user to make decisions for their particular business usecases on what DDL should be safe for them to run.

Ideally this would also include a modification to the engine in order to support the separation of `suggested_ddl` to `suggested_safe_ddl` & `suggested_unsafe_ddl`.

**Additional context**

Right now all `share` related DDL is considered `unsafe` unless it's an `ALTER` to an existing `share`. This works fine for regular sharing as you define who has access to a `share` upfront, which is a potentially dangerous action. However for shares in the Marketplace, you don't define sharing targets upfront, so the `CREATE` ddl is safe.

For me I'd like to define `safe` as:
- `CREATE`

`unsafe`:
- `ALTER`
- `DROP`

**Comment by littleK0i** [comment]
You may create other shares using different owner role. SnowDDL only manages objects which are explicitly owned by SnowDDL admin role. It completely ignores objects owned by other roles.

It applies to all types of objects, including shares.
