### ISSUE TITLE
Primary keys completely dropped while redefining PK and changing datatype of one of PK columns 

### ISSUE THREAD

**Issue by zhyzhkea** [littleK0i/SnowDDL#47]
**Describe the bug**
Primary keys completely dropped while redefining PK and changing the datatype of one of PK columns 

**Expected behavior**
New PK would be created

**Attach log**
(snowddl) linux@Envyx360:/mnt/c/work/snowflake/snowddl$ snowddl -c /mnt/c/work/snowflake/snowddl/SnowDDL/_config/sample01_01 -a kqbcpkv-******* -u snowddl -p SNOWDDL --apply-unsafe plan
2023-07-13 11:46:10.711 - INFO - Snowflake version = 7.23.1 (STANDARD), SnowDDL version = 0.17.0
2023-07-13 11:46:10.711 - INFO - Account = *******, Region = AWS_US_WEST_2
2023-07-13 11:46:10.711 - INFO - Session = 9456929578749958, User = SNOWDDL
2023-07-13 11:46:10.711 - INFO - Role = SNOWDDL_ADMIN, Warehouse = None
2023-07-13 11:46:10.711 - INFO - Roles in session = SYSADMIN,SECURITYADMIN
2023-07-13 11:46:10.711 - INFO - ---
2023-07-13 11:46:14.452 - INFO - Resolved TABLE [SNOWDDL_DB.BOOKINGS.SEATS]: REPLACE
2023-07-13 11:46:15.036 - INFO - Resolved PRIMARY_KEY [SNOWDDL_DB.BOOKINGS.SEATS(AIRCRAFT_CODE,SEAT_NO,FARE_CONDITIONS)]: CREATE
2023-07-13 11:46:15.036 - INFO - Resolved PRIMARY_KEY [SNOWDDL_DB.BOOKINGS.SEATS(AIRCRAFT_CODE,SEAT_NO)]: DROP
2023-07-13 11:46:22.472 - INFO - Executed 0 DDL queries, Suggested 3 DDL queries
--- Suggested DDL ---

CREATE OR REPLACE TABLE "SNOWDDL_DB"."BOOKINGS"."SEATS"
(
      "AIRCRAFT_CODE" VARCHAR(3) NOT NULL COMMENT 'Aircraft code, IATA'
    , "SEAT_NO" VARCHAR(4) NOT NULL COMMENT 'Seat number'
    , "FARE_CONDITIONS" VARCHAR(8) NOT NULL COMMENT 'Travel class'
)
COMMENT = 'Seats define the cabin configuration of each aircraft model. Each seat is defined by its number (seat_no) and has an assigned travel class (fare_conditions): Economy, Comfort or Business.'
COPY GRANTS
AS
SELECT
      "AIRCRAFT_CODE"::VARCHAR(3) AS "AIRCRAFT_CODE"
    , "SEAT_NO"::VARCHAR(4) AS "SEAT_NO"
    , "FARE_CONDITIONS"::VARCHAR(8) AS "FARE_CONDITIONS"
FROM "SNOWDDL_DB"."BOOKINGS"."SEATS";

ALTER TABLE "SNOWDDL_DB"."BOOKINGS"."SEATS" ADD PRIMARY KEY ("AIRCRAFT_CODE", "SEAT_NO", "FARE_CONDITIONS");

**ALTER TABLE "SNOWDDL_DB"."BOOKINGS"."SEATS" DROP PRIMARY KEY;**

(snowddl) linux@Envyx360:/mnt/c/work/snowflake/snowddl$ snowddl -c /mnt/c/work/snowflake/snowddl/SnowDDL/_config/sample01_01 -a kqbcpkv-******** -u snowddl -p SNOWDDL --apply-unsafe apply
2023-07-13 11:57:37.224 - INFO - Snowflake version = 7.23.1 (STANDARD), SnowDDL version = 0.17.0
2023-07-13 11:57:37.224 - INFO - Account = *******, Region = AWS_US_WEST_2
2023-07-13 11:57:37.224 - INFO - Session = 9456929578737678, User = SNOWDDL
2023-07-13 11:57:37.224 - INFO - Role = SNOWDDL_ADMIN, Warehouse = None
2023-07-13 11:57:37.224 - INFO - Roles in session = SYSADMIN,SECURITYADMIN
2023-07-13 11:57:37.224 - INFO - ---
2023-07-13 11:57:39.407 - INFO - Resolved TABLE [SNOWDDL_DB.BOOKINGS.SEATS]: REPLACE
2023-07-13 11:57:39.988 - WARNING - Resolved PRIMARY_KEY [SNOWDDL_DB.BOOKINGS.SEATS(AIRCRAFT_CODE,SEAT_NO,FARE_CONDITIONS)]: ERROR
(
    message   =>  SQL compilation error:
primary key already exists for table 'SEATS'
    errno     =>  1451
    sqlstate  =>  42601
    sfqid     =>  01ad9ad1-0001-b0bc-0021-99070037108a
    sql       =>  ALTER TABLE "SNOWDDL_DB"."BOOKINGS"."SEATS" ADD PRIMARY KEY ("AIRCRAFT_CODE", "SEAT_NO", "FARE_CONDITIONS")
)
2023-07-13 11:57:40.103 - INFO - Resolved PRIMARY_KEY [SNOWDDL_DB.BOOKINGS.SEATS(AIRCRAFT_CODE,SEAT_NO)]: DROP
2023-07-13 11:57:42.917 - INFO - Executed 1 DDL queries, Suggested 1 DDL queries
--- Suggested DDL ---

CREATE OR REPLACE TABLE "SNOWDDL_DB"."BOOKINGS"."SEATS"
(
      "AIRCRAFT_CODE" VARCHAR(3) NOT NULL COMMENT 'Aircraft code, IATA'
    , "SEAT_NO" VARCHAR(4) NOT NULL COMMENT 'Seat number'
    , "FARE_CONDITIONS" VARCHAR(8) NOT NULL COMMENT 'Travel class'
)
COMMENT = 'Seats define the cabin configuration of each aircraft model. Each seat is defined by its number (seat_no) and has an assigned travel class (fare_conditions): Economy, Comfort or Business.'
COPY GRANTS
AS
SELECT
      "AIRCRAFT_CODE"::VARCHAR(3) AS "AIRCRAFT_CODE"
    , "SEAT_NO"::VARCHAR(4) AS "SEAT_NO"
    , "FARE_CONDITIONS"::VARCHAR(8) AS "FARE_CONDITIONS"
FROM "SNOWDDL_DB"."BOOKINGS"."SEATS";

(snowddl) linux@Envyx360:/mnt/c/work/snowflake/snowddl$ 	

**Attach YAML config (if applicable)**
columns:
  aircraft_code:
    type: VARCHAR(3) NOT NULL
    comment: "Aircraft code, IATA"

  seat_no:
    type: VARCHAR(4) NOT NULL
    comment: "Seat number"

  fare_conditions:
    type: VARCHAR(8) NOT NULL
    comment: "Travel class"

primary_key: [aircraft_code, seat_no, fare_conditions]

foreign_keys:
  - columns: [aircraft_code]
    ref_table: aircrafts_data
    ref_columns: [aircraft_code]

comment: >-
  Seats define the cabin configuration of each aircraft model.
  Each seat is defined by its number (seat_no) and has an assigned travel class (fare_conditions): Economy, Comfort or Business.

create or replace TABLE SNOWDDL_DB.BOOKINGS.SEATS (
	AIRCRAFT_CODE VARCHAR(3) NOT NULL COMMENT 'Aircraft code, IATA',
	SEAT_NO VARCHAR(4) NOT NULL COMMENT 'Seat number',
	FARE_CONDITIONS VARCHAR(10) NOT NULL COMMENT 'Travel class',
	foreign key (AIRCRAFT_CODE) references SNOWDDL_DB.BOOKINGS.AIRCRAFTS_DATA(AIRCRAFT_CODE)
)COMMENT='Seats define the cabin configuration of each aircraft model. Each seat is defined by its number (seat_no) and has an assigned travel class (fare_conditions): Economy, Comfort or Business.'
;

Resulting table after "apply":
create or replace TABLE SNOWDDL_DB.BOOKINGS.SEATS (
	AIRCRAFT_CODE VARCHAR(3) NOT NULL COMMENT 'Aircraft code, IATA',
	SEAT_NO VARCHAR(4) NOT NULL COMMENT 'Seat number',
	FARE_CONDITIONS VARCHAR(10) NOT NULL COMMENT 'Travel class',
	foreign key (AIRCRAFT_CODE) references SNOWDDL_DB.BOOKINGS.AIRCRAFTS_DATA(AIRCRAFT_CODE)
)COMMENT='Seats define the cabin configuration of each aircraft model. Each seat is defined by its number (seat_no) and has an assigned travel class (fare_conditions): Economy, Comfort or Business.'
;

**Comment by littleK0i** [comment]
Thank you for spotting this problem.

Previously Snowflake allowed to define multiple PRIMARY KEYs for a single table. Obviously, it was a bug, and I am glad it was fixed.

I've adjusted the logic for `PRIMARY_KEY` resolver. Now it should produce commands in the correct order: `DROP PRIMARY KEY` followed `ADD PRIMARY KEY`. The update is available since `0.17.1`.

However, you have an additional problem here. When you change data type of the column, normally the whole table has to be re-created from scratch. It is a fundamental limitation of Snowflake.

SnowDDL produces DDL commands to do that, but it does not replace tables automatically. So you have two options to handle this:

1. Run SnowDDL to apply "safe" commands and to suggest "unsafe" and "replace table" commands. Review & apply suggested commands manually. And re-run SnowDDL again to create keys.
2. Add CLI arguments `--apply-unsafe --apply-replace-table`. Tables will be replaced by SnowDDL, and primary keys will be re-created in the correct order. However, it consumes credits and it may take a long time, depending on table size.

**Comment by zhyzhkea** [comment]
Thanks, I will try the new version and report.

**Comment by littleK0i** [comment]
@zhyzhkea , so.. did it work? Maybe we can close this issue.

Thanks!

**Comment by zhyzhkea** [comment]
Sorry for the late update. It worked out well. Thanks.
