### ISSUE TITLE
post to Snowflake login url /session/v1/login-request hanging, failing

### ISSUE THREAD

**Issue by JohnL4** [littleK0i/SnowDDL#55]
This is almost a support request rather than a bug, but I can't figure out what's going on from the docs, so maybe it could be considered a bug in the docs?

**Describe the bug**
I'm attempting run sample01 in the "Getting Started" guide, and I can't run the initial snowddl 'apply' command for sample01_01 because the authentication appears to be failing. I've created a trial account w/snowflake and gotten my account identifier from the account selector popup.  Command line is:

```
snowddl -c sample01_01 -a "GAJVKZJ.OYB90337" -u SNOWDDL -p thisIsNotMyPassword --apply-unsafe --log-level DEBUG plan
```

(I also tried it without quotes around the account identifier.)

My current working dir. is 
```
C:\Users\thisIsNotMyUserName\appdata\Local\Programs\Python\Python311\Lib\site-packages\snowddl\_config
```

**Expected behavior**
I expected sample01_01 to get applied to my trial Snowflake account.

**Attach log**
Attach log produced by SnowDDL CLI interface or by your application. Please make sure to include "context" information which is normally produced at the beginning of the log.

[snowddl-out.txt](https://github.com/littleK0i/SnowDDL/files/12490726/snowddl-out.txt)

**Attach YAML config (if applicable)**
It is the included sample01_01 that came with the install.

**Comment by littleK0i** [comment]
The account name should be specified with hyphen: `GAJVKZJ-OYB90337`.

Some more info on this: https://docs.snowflake.com/en/user-guide/admin-account-identifier

Thank you.

**Comment by JohnL4** [comment]
Aha! Thank you!
