### ISSUE TITLE
Query Tag to indicate in Snowflake Query History which SQL is generated by SnowDDL (and which version)

### ISSUE THREAD

**Issue by bchin3** [littleK0i/SnowDDL#59]
**Is your feature request related to a problem? Please describe.**
As usage of SnowDDL (single-db) is being used by more developers across different teams in our organization, we are looking to leverage Snowflake Query History to
- identify who is using SnowDDL (so we can support them internally)
- verify which versions of SnowDDL teams are using (so we can identify outdated versions)
- give users an easier way to filter by (or filter out) SnowDDL executions in query history

**Describe the solution you'd like**
Have SnowDDL set a query tag (e.g. "SnowDDL 0.21.0") when executing so that it is visible in the Query Tag field in Snowflake Query History.  Especially when being run by automated processes/logins during CI/CD.  Also will help us identify teams that are still using older versions of SnowDDL.   Perhaps also give us the flexibility to also add a custom string to the query tag as well.

`--query-tag` This results in query tag set to `SnowDDL 0.21.0`
`--query-tag "this is a query tag" ` This will results in the query tag text appended to the default text to `SnowDDL 0.21.0 this is a query tag`

**Describe alternatives you've considered**
Setting Query Tag value at the user level is not a consistent solution for this since a single user login may execute queries that are not via SnowDDL, and we want to identify only their SnowDDL executions (and which version they are running).

**Additional context**
N/A

Thanks for considering

**Comment by littleK0i** [comment]
I believe there is a special connection option called `application`, which should be used to identify a specific app.

This is how it looks in Python connector code:
```python
        if "application" not in kwargs:
            if ENV_VAR_PARTNER in os.environ.keys():
                kwargs["application"] = os.environ[ENV_VAR_PARTNER]
            elif "streamlit" in sys.modules:
                kwargs["application"] = "streamlit"
```

You may access information about application using system view SESSIONS: https://docs.snowflake.com/en/sql-reference/account-usage/sessions

Maybe it would be more appropriate to pass `SnowDDL 0.21.0` string using the `application` option instead of putting it into query tag.

---

But I definitely like the general idea of adding query tag support. I think it would be more natural to pass query tag from CLI option "as is" without any changes.

As far as I know, many customers use JSON-format or `key=value;` format for query tags so automatic concatenation with plain string would make such customers unhappy.

**Comment by littleK0i** [comment]
I guess, we can also add ENV variable `SNOWFLAKE_QUERY_TAG`, which can be used instead of passing `--query-tag` in CLI. Similar to `SNOWFLAKE_ACCOUNT`, `SNOWFLAKE_USER`, etc.

**Comment by littleK0i** [comment]
@bchin3 , I've pushed a small update with version `0.21.0`.

Application is now explicitly set to `SnowDDL <version>`. You may access it by joining `QUERY_HISTORY` view to `SESSIONS` view using column `SESSION_ID`. There is a significant update time lag for `SESSIONS` view, but it should be OK for not time-critical monitoring.

Also, `--query-tag` CLI option is now available, as well as `SNOWFLAKE_QUERY_TAG` environment variable. You may use it to build any `QUERY_TAG` value you want.

Please let me know if it works for you! And thanks again for raising this suggestion.

**Comment by littleK0i** [comment]
Btw, if you actively use SnowDDL in production, I highly suggest to "pin" the specific version.

Snowflake may randomly change stuff sometimes, and I may introduce some changes in SnowDDL in response. Sometimes it might not be possible to maintain backwards compatibility, so I suggest to check CHANGELOG file first and test new versions in your specific environment before allowing devs to use it.
