### ISSUE TITLE
Add Error Integration Parameter to Pipe Config

### ISSUE THREAD

**Issue by christopher-leigh** [littleK0i/SnowDDL#65]
**Is your feature request related to a problem? Please describe.**
I would like to be able to manage my [error integrations ](https://docs.snowflake.com/en/user-guide/data-load-snowpipe-errors)within my Snowpipe configs. 

**Describe the solution you'd like**
Add an additional input to the pipe config like so:

- **error_integration (str)** - name of notification integration

**Describe alternatives you've considered**
Currently having to manually alter the pipe after SnowDDL creates the pipe so I can set the error integration for my pipes.

**Additional context**
N/A

**Comment by littleK0i** [comment]
@christopher-leigh , done in `0.22.1`.

Also, I've added tests for pipes and updated documentation page.

**Comment by christopher-leigh** [comment]
You are a legend 🙏 thank you so much for addressing this so quickly!

Couple of things:

- Just checked out the doc site and noticed it hasn't updated yet, is that intentional?
- One nuance I ran into when setting up error notifications is that I had to grant the schema owner usage on the notification integration. Otherwise the notifications were not generating and publishing to my SNS topic. I found this step in [this](https://community.snowflake.com/s/article/Troubleshooting-Error-Notifications-for-Snowpipe-and-Tasks-Amazon-SNS) troubleshooting guide. Took a glance through the commit history and don't see this usage grant taking place, but I very likely could just be missing something!

**Comment by littleK0i** [comment]
@christopher-leigh , doc page updates seems to be delayed due to some issues with GitBook (SaaS which hosts documentation). It looks good right now.

Regarding to `USAGE` privilege on notification integration, currently it is supposed to be granted to SnowDDL admin role. This method works well for other object types: https://docs.snowddl.com/guides/other/integrations

If it is not good enough for pipes, I'll consider removing `GRANT OWNERSHIP ON FUTURE PIPES` or automatic re-granting of `USAGE` to schema owners roles.

The first approach is straightforward. All pipes will be owned directly by SnowDDL admin role, similar to stages. But schema owners will no longer be able to pause pipes.

The main problem with the second approach is related to human users with access to schema owner roles. If human users automatically get `USAGE` on the whole notification integration, they might be able to send any messages they want.

**Comment by chris-leigh-dignifi** [comment]
Gotcha -- that makes sense! I also see it updated in the documentation now. I will let you know if we have any issues or feedback with the current implementation. I am working deploying it to our environment now!

**Comment by littleK0i** [comment]
@chris-leigh-dignifi , so .. did it work with current approach to notification integration? Are pipes functioning correctly?

Thank you.

**Comment by littleK0i** [comment]
@chris-leigh-dignifi , ok, one more case of Snowflake weirdness. Not a problem.

In theory, we can create an automated solution:

1. For each schema, identify all tasks and pipes with "error_integration" parameter.
2. Remove duplicates, get list of unique notification integrations.
3. Grant usage on unique notification integrations to schema owner role.

So everything will be handled automatically.

---

What I really dislike about Snowflake logic here is how lack of grant causes a "silent" failure. There are no errors during creation of pipe or task object. Things just do not work, and you may not notice it for a long time.

I'll consider raising a support case to add an explicit check and explicit error message at least during object creation. A lot of people may fall into this trap.

**Comment by littleK0i** [comment]
On a second thought ... explicit is better than implicit, and Snowflake keeps adding new integration types all the time.

I think it might be better to add an explicit parameter `owner_integration_usage` (in addition to existing `owner_schema_read`, `owner_schema_write`).

All integrations seems to be sharing the same namespace and the same approach to "USAGE" privilege, so there is no need to specify each integration type separately. At least for now.

**Comment by littleK0i** [comment]
@christopher-leigh , I've pushed the update. Version `0.23.1`.

Here is an example of `params.yaml` file which should be created in schema config directory to grant USAGE.

```
owner_integration_usage:
  - test_notification_integration
```

I'll update the documentation soon.

**Comment by christopher-leigh** [comment]
Awesome. I'll wait until the documentation is updated and then will test this out!

**Comment by littleK0i** [comment]
Closing this issue. Error integration was implemented for pipes and should work as expected.
