### ISSUE TITLE
Tasks, views, functions and procedures body text from script file

### ISSUE THREAD

**Issue by oz-chewie** [littleK0i/SnowDDL#67]
**Is your feature request related to a problem? Please describe.**
For tasks, views, functions and procedures it is a win to have code and yaml in separate files.  This allows for easier testing and dev work and avoids inline quoting and formatting that ends up in repo code.

**Describe the solution you'd like**
For tasks, views, functions and procedures support a new `body` option of either:
- a prefilter script for yaml that can substitute in code (SQL, Python, JS, etc) for a tag (eg: "{FOO_FUNCTION_CODE}", or
- a yaml file reference

**Describe alternatives you've considered**
Inline appears to be the only way to insert code into SnowSSL yaml for now.

**Comment by littleK0i** [comment]
It is currently available via `!include` custom tag: https://docs.snowddl.com/basic/yaml-tag-include

**Comment by oz-chewie** [comment]
Oh super nice!  Would help if I could read :/
