### ISSUE TITLE
External Access Integration Not Considered in snowddl-singledb Execution

### ISSUE THREAD

**Issue by aminebr** [littleK0i/SnowDDL#85]
**Is your feature request related to a problem? Please describe.**
I would love some guidance on the following use case: 

I am using **snowddl-singledb** and I want to create an **external_access_integration** : 

this is my folder tree : 
````
.
├── datamart
│   └── iam
│       ├── network_rule
│       │   └── redis_egress_rule.yaml
│       └── table
│           ├── organization.yaml
│           ├── role.yaml
│           ├── user.yaml
│           └── user_roles.yaml
├── external_access_integration.yaml
└── snowddl.sh
````

my snowddl.sh will init my variables and launch this command :
````
snowddl-singledb -w $SNOWFLAKE_WAREHOUSE --show-sql --config-db datamart --target-db $DATAMARTDB --include-object-types TABLE,NETWORK_RULE,EXTERNAL_ACCESS_INTEGRATION --placeholder-values="{\"datamart_db\": \"$DATAMARTDB\"}" $2 $3 $4
````

I execute this command : 
````
./snowddl.sh ../terraform/dp_iam_dev.tfvars --apply-unsafe --apply-replace-table apply
````
it perfectly creates the tables and the network rule but it **does not take into consideration** the external_access_integration.yaml

**Describe the solution you'd like**
I want the external_access_integration.yaml to be taken into account
if possible the external_access_integration to be able to detect the database and to not provide it since I am in a singleDB

like in the example in the documentation: 

````
redis_access_integration:
  allowed_network_rules:
    - iam.redis_egress_rule
````

**Describe alternatives you've considered**

create the external_access_integration like I am creating a a network rule 
and since I am in /database/schema/
I don't need to specify the database and schema anymore 
````
.
├── datamart
│   └── iam
│       ├── external_access_integration
│       │   └── redis_access_integration.yaml
│       ├── network_rule
│       │   └── redis_egress_rule.yaml
│       └── table
│           ├── organization.yaml
│           ├── role.yaml
│           ├── user.yaml
│           └── user_roles.yaml
└── snowddl.sh
````

**Additional context**

**Comment by littleK0i** [comment]
Snowflake made a strange decision to implement EXTERNAL ACCESS INTEGRATION as global account-level object, even if it should clearly belong to schemas. Naturally, account-level objects are out of scope for SingleDB mode.

What you can try to do instead:

1. Switch to standard mode.
2. Create external access integrations manually and grant to SnowDDL admin role.

Here is the place in code which describes resolver sequences for normal mode and SingleDB mode:
https://github.com/littleK0i/SnowDDL/blob/master/snowddl/resolver/__init__.py#L48-L122

**Comment by littleK0i** [comment]
It might be a good idea to raise a ticket for Snowflake support and ask for an alternative schema-only implementation of external access. They should be able to rework it when enough people point this out.

**Comment by littleK0i** [comment]
I'll close it for now, since it is mostly related to Snowflake design decisions around integrations.
