### ISSUE TITLE
Please support --refresh-stage-encryption in SingleDB mode.

### ISSUE THREAD

**Issue by josdotso** [littleK0i/SnowDDL#93]
**Is your feature request related to a problem? Please describe.**
Refresh stage encryption is an option in the main CLI but not in SingleDB CLI. 

**Describe the solution you'd like**
Please add the option `  --refresh-stage-encryption       Additionally refresh stage encryption parameters for existing external stages` to singledb mode.

**Describe alternatives you've considered**
I will drop and recreate the resources for now I guess.

**Additional context**
I have several stages that need encryption turned on. 

thanks

**Comment by littleK0i** [comment]
@josdotso , added `--refresh-stage-encryption` and `--refresh-secrets` in `0.25.2`. Please give it a try.

**Comment by josdotso** [comment]
Thank you!
