### ISSUE TITLE
ALTER TABLE DROP FOREIGN KEY after DROP TABLE

### ISSUE THREAD

**Issue by JohnL4** [littleK0i/SnowDDL#98]
**Describe the bug**
So, ``snowddl plan`` generated SQL that has a DROP TABLE occurring before an ALTER TABLE DROP FOREIGN KEY for the same table. That seems problematic. Snowflake threw an error (but no line number) when I used snowsql to submit the generated SQL. (There's also a DROP VIEW for a view against the same table occurring at the end of the generated SQL, but I guess Snowflake didn't have a problem with that.)

**Expected behavior**
``snowddl plan`` generates SQL that runs correctly, not attempting to ALTER objects that have been DROPped.

**Attach log**
Sadly, this was done in an Azure pipeline w/no log, and if I re-run it now, the table is gone, so I'm guessing there won't be a DROP statement generated again.

**Attach YAML config (if applicable)**
n/a

-------------------------------
I know this is a very light ticket, and feel free to just close it, but I'm wondering if it might trigger a "silly me, I'm altering tables after I drop them" thought. I'll also go poke around in the source code a bit.

**Comment by JohnL4** [comment]
https://github.com/littleK0i/SnowDDL/blob/2ad3fe9da68fb5739427a33c41fd3fe59efc8f2b/snowddl/resolver/foreign_key.py#L96

ALTER TABLE IF EXISTS, maybe?

**Comment by littleK0i** [comment]
Yes, it is an interesting problem. It is definitely on the roadmap and should be resolved at some point.

It happens only when you try to apply "suggested" SQL automatically, without reviewing it first. There are potential solutions:

**(1) Keep shared cache of "dropped" objects. Add explicit cache checks to all DROP commands.**
The main problem here is the introduction of "shared state" across resolvers. Currently there is no shared state, and each resolver operates independently.

Also, it is possible to make a mistake in dropping rules, or Snowflake might change their logic of implicit drops. It opens the possibility to skip some DROPs and produce incorrect results.

**(2) Implement option to add IF EXISTS to DROP commands**
This might work very well for most object types. But some object types may not support it. For example, it is likely not supported for FOREIGN KEYS.

Also, if something is wrong with the plan, and object no longer exists, we'll never know. "Object does not exist" errors will be silenced.

---

So, the current implementation is the most obvious and straightforward, even if it may produce technically incorrect "Suggested SQL" in case of implicit drops.

When you apply suggested commands manually, which is highly recommended for production system, you'll see the problem and adjust commands easily. When you apply commands via SnowDDL with `--apply-unsafe` flag, problem does not occur at all.

I am still debating if the amount of code and extra test coverage is worth it to improve use case which is probably valid, not optimal. Delayed automated execution of "plan" SQL commands may cause damage to your account if some objects were changed between "plan" generation and actual application of it.

**Comment by littleK0i** [comment]
Hmm, I guess, we can find a middle ground with the following approach:

1) Add `IF EXISTS` to most DROP-like statements.
2) Check the response during execution of DROP-like statements inside SnowDDL. Raise a warning if statement returned "does not exist" string, since it is not supposed to happen during normal operation.

Naturally, during `plan` action "does not exist" check will be skipped.

In theory, it should help users who use SnowDDL in a slightly different way, but it should not "hide" errors during normal operation.

**Comment by JohnL4** [comment]
> **(1) Keep shared cache of "dropped" objects. Add explicit cache checks to all DROP commands.** 

Yeah, thought about the cache solution. I wouldn't want to code it :) which I guess is a warning sign.

> **(2) Implement option to add IF EXISTS to DROP commands** 

I think I might actually test this next week.

> So, the current implementation is the most obvious and straightforward, even if it may produce technically incorrect "Suggested SQL" in case of implicit drops.

Another possibility is to post-process the generated SQL to fix it up with IF EXISTS clauses (or maybe comment delimiters) where possible. It's a more heinous kludge, but if it turns out to be the only fix....

Will investigate ``--apply-unsafe``, thanks!

**Comment by littleK0i** [comment]
After some testing, I've realised "DROP IF EXISTS" is still going to raise exceptions if schema or database does not exist.

For example:
```
DROP TABLE test_db.test_schema.test_table;
```

If `test_db.test_schema` exists, it works. Statement runs successfully, and response message is:
```
Drop statement executed successfully (TEST_TABLE already dropped).
```

But if database `test_db` or schema `test_db.test_schema` do not exist, statement fails with:
```
Database 'TEST_DB' does not exist or not authorized.
```

So.. even if we add `IF EXISTS` to every drop statement, it does guarantee anything.

---

Also, `ALTER TABLE IF EXITS ... DROP CONSTRAINT ...` does not really tell us if constraint existed before. The response is always the same:
```
Statement executed successfully.
```

Which is not great, since we cannot detect incorrect behaviour during execution.

---

It seems like Snowflake makes things quite difficult. "Cache" solution might be the only option. SnowDDL already has it in place for DATABASE and SCHEMA objects, but other object types might be more difficult.

Let me think about it for some time. Maybe I'll find a way to simplify logic and make cache easier to manage and less error prone.

**Comment by JohnL4** [comment]
Yep, just came here with my own sad discovery.

```
DROP TABLE FOO;
ALTER TABLE IF EXISTS FOO DROP FOREIGN KEY ("BAR_KEY");
```

Fails on the 2nd line with a compilation error ``invalid identifier 'BAR_KEY'``. I guess Snowflake can't (yet) do conditional compilation or whatever would be required.

So, at this point, it's either the caching solution or post-processing the generated SQL on my side. Or adding more hairy conditional logic in the generated SQL which re-consults the metadata just before executing a DROP or ALTER statement. Or something entirely different.

--------------

In my particular case, the d/b will never be dropped and I don't think the schema will be, either, although I'm not sure what will happen if the schema is renamed. I guess snowddl will think that's a schema drop and the creation of entirely new schema? That would be bad for us, but also extremely rare, so we could scan for DROP SCHEMA statements and flag those for manual intervention.

**Comment by littleK0i** [comment]
Renaming anything is DROP and CREATE for any declarative tool without state. Name is the only available identifier for objects.

But you may keep a small SQL file for manual changes during release. You'll have some of these changes anyway, like `UPDATE TABLE`. Renaming can be a part of it, and it should be applied before SnowDDL run.

In theory, for schemas you should also rename schema roles and / or use CLI option `--refresh-future-grants`.

**Comment by littleK0i** [comment]
I expect to push "intention cache" feature in the next few days. It was relatively easy to implement for `DROP` commands.

But I am not sure about `REPLACE` commands, if we want to complete this feature. Replacing a table is technically DROP + CREATE, and it requires associated references to be applied again (e.g. MASKING POLICY).

Even if it might be possible to take REPLACE into account, the code is going to be quite complex.

**Comment by littleK0i** [comment]
@JohnL4 , try version `0.26.0`.

Drops for table constraints and stage files should no longer appear during `plan` action if parent object is expected to be dropped.

**Comment by JohnL4** [comment]
Thanks, I will!

When you said "intention cache", I sort of thought you'd provide a facility to allow the user to _specify_ that a drop/create pair is actually a rename. Like, maybe in the yaml for an object, include a property for old name(s). That way, instead of generating a drop/create pair, instead generate a RENAME statement?

In my case, it'd be easy to merge in a separate yaml file maintained by our devs, merging it into the yaml generated by ``snowddl-convert`` (read our yaml , read convert yaml, add attributes, write convert yaml back out).

If that wasn't your concept, yes, I can imagine it would be hard to read the developer's mind to figure out if drop/create is really a rename. In fact, I'm not sure it's possible to do reliably w/out human input.

I guess the same would apply to columns, too, not just tables. Not sure about other objects.

**Comment by littleK0i** [comment]
Managing renames via config is very difficulty. I'll try to explain why.

1. What if we want to swap names? Table `A -> B, B -> A`. Both names exist before execution.
2. What if we want to change not only name, but also data type for a column?
3. What if we want to move table into another schema, but new schema is TRANSIENT, and table should become transient as well?
4. What if we want to add some custom data transformation on top? It is quite common with renames.
5. What if script crashes in the middle of execution? How would we know which renames were applied and which renames were not applied without becoming "stateful" and storing the status of commands somewhere?
6. What is going to happen with `old_name` in config after our renames were applied? Should we keep it forever? Should we remember to remove it manually?

If you start thinking about all the edge cases, you quickly realize that there is massive subset of custom operations which realisitically cannot be fully automated. It means that we need a way to apply these operations manually from time to time. And if we already going to apply something manually sometimes, RENAME can be a part of it.

In theory, what we can do is to suggest an "official" way of maintaining SQL files for all types of manual transformations. Currently it is completely out of scope for SnowDDL.

**Comment by JohnL4** [comment]
Just getting back to this. 

Fair enough, generalized renames are complex and probably beyond scope. My particular use case is constrained (I hope), and I can write post-processing code to detect the need for manual intervention (I hope).

I'll let you know how 0.26.0 works out.
